# Generated by Django 5.0.1 on 2024-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='review',
            name='movie_details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
